name: Deploy app
on:
  workflow_run:
    workflows:
      - Build and Push Docker Image
    types:
      - completed
jobs:
  deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url:  ${{ secrets.URL_WEBHOOK }}
          method: 'POST'
          bearerToken: ${{ secrets.TOKEN_WEBHOOK }}
